# Generated by Django 3.1.14 on 2022-01-11 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Имя по-русски')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, default='Описание', verbose_name='Описание')),
                ('title_en', models.CharField(blank=True, max_length=100, verbose_name='Имя по-английски')),
                ('title_jp', models.CharField(blank=True, max_length=100, verbose_name='Имя по-японски')),
                ('previous_evolution', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Предыдущая эволюция')),
            ],
            options={
                'verbose_name': 'Покемон',
                'verbose_name_plural': 'Покемоны',
            },
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('appeared_at', models.DateTimeField(blank=True, default=None, verbose_name='Появился')),
                ('disappeared_at', models.DateTimeField(blank=True, default=None, verbose_name='Исчезнет')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Уровень')),
                ('health', models.PositiveIntegerField(default=1, verbose_name='Здоровье')),
                ('strength', models.PositiveIntegerField(default=1, verbose_name='Сила')),
                ('defence', models.PositiveIntegerField(default=1, verbose_name='Защита')),
                ('stamina', models.PositiveIntegerField(default=1, verbose_name='Выносливость')),
                ('pokemon', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entity', to='pokemon_entities.pokemon', verbose_name='Покемон')),
            ],
            options={
                'verbose_name': 'Вид покемона',
                'verbose_name_plural': 'Видов покемонов',
            },
        ),
    ]
